### ISSUE TITLE
Convert txt2tags files to Markdown or HTML

### ISSUE THREAD

**Issue by aureliojargas** [aureliojargas/aurelio.net#11]
My goal is to make the site simpler. See issue #1.

Currently, there are four kinds of content files in my website: 

```console
$ find . -name '*.t2t'  | wc -l
274
$ find . -name '*.md'   | wc -l                                                                   
138
$ find . -name '*.html' | wc -l                                                                 
1401
$ find . -name '*.txt'  | wc -l                                                                  
114
$
```

I would be happier if I could use just HTML and txt, and never have to convert anything. But life's hard, and I need a tool like Jekyll to automate things.

For now, I'm trying to reduce complexity.

The ideia is to remove the need to have txt2tags (my own tool) to convert files to HTML. It's kinda sad making this move, but Markdown is well supported everywhere an has excellent tooling. I can even try the GitHub Pages or GitLab Pages hosting in the future and save hosting costs. I also don't want to keep maintaining txt2tags forever, so it gotta go :(

- Some very very old txt2ags files I will never update, they are legacy. Those could be converted to HTML and be done.

- Other txt2tags files are areas of the site I still have interest in updating, so maybe Markdown would be best.

I still don't know if I will get 100% done, but I'll try.

Those are the site areas with txt2tags files:

- [x] baterna
- [x] c0d4r3
- [x] correria
- [x] curso
- [x] doc
- [x] email
- [x] fvm
- [x] include
- [x] mac
- [x] misc
- [x] moneylog
- [x] musica
- [x] projects
- [x] rac
- [x] sed
- [x] shell
- [x] viagem
- [x] vim
 
To see the updated area list, run:

 ```
find . -name '*.t2t' | grep -v '^\./_site/' | cut -d/ -f2 | sort | uniq
```

**Comment by Walckiers** [comment]
Oh dear! Please dont abandon t2t !!
r.

**Comment by aureliojargas** [comment]
Current status:

```console
$ find . -name '*.t2t' | grep -v '^\./_site/' | wc -l                                                                            
186
```

**Comment by Walckiers** [comment]
As of 2017.11.27 08:18:09 C.E.T.
Useful links for txt2tags mourners:-

STILL THERE
    https://txt2tags.org/tips.html
    https://txt2tags.org/userguide/thethreeuserinterfacesguiwebandcommandline
AND
    https://linux.die.net/man/1/txt2tags
    https://mostlylinux.wordpress.com/textanddocument/txt2tagscheatsheet
    https://sourceforge.net/p/txt2tags/mailman/txt2tags-list/?page=1
R.I.P.
    http://bugs.txt2tags.org
    https://txt2tags.org/rules.html

**Comment by aureliojargas** [comment]
There are some low hanging fruits there:

```console
$ find . -name '*.t2t' | grep -v '^\./_site/' | cut -d/ -f2 | sort | uniq -c | sort -nr
     36 rac
     28 projects
     24 email
     21 moneylog
     14 include
     13 fvm
     13 doc
     10 shell
      9 correria
      7 vim
      7 curso
      2 c0d4r3
      1 baterna
$
```

**Comment by aureliojargas** [comment]
Hey @Walckiers , I've fixed the missing `/rules.html` URL (done in https://github.com/txt2tags/website/commit/cb63754573523acb3a6223f104c7dd31da9fad91). Thanks for the report!

**Comment by aureliojargas** [comment]
Current status:

```console
$ find . -name '*.t2t' | grep -v '^\./_site/' | cut -d/ -f2 | sort | uniq -c | sort -nr
     36 rac
     28 projects
     21 moneylog
     11 include
     10 shell
      9 correria
      7 curso
$
```

**Comment by aureliojargas** [comment]
Current status:

```console
$ find . -name '*.t2t' | grep -v '^\./_site/' | cut -d/ -f2 | sort | uniq -c | sort -nr
     36 rac
     28 projects
      6 shell
      2 curso
```

**Comment by Walckiers** [comment]
Long may txt2tags flourish!
    Last year, txt2tags made every one of the pages in our  Advent Calendar 
     http://users.skynet.be/watermael/nvrs_hri-ggAdventCalendar2017.html 
    And the t2t pages for our 2018 Calendar are coming  along nicely...
    Many thanks!
   Richard H

     Yours 
     Richard H

**Comment by aureliojargas** [comment]
After more than a year of commits, it's finally done.

A few were converted to Markdown, most were converted to plain HTML.

Now the only txt2tags files left in the repo are historical versions for the `/shell/dialog/` document and two MagicPoint files that I don't really want to touch:

```
./curso/material/desenvolvedor/desenvolvedor.t2t
./curso/sdsl-2/desenvolvedor/desenvolvedor.t2t
./shell/dialog/index-v1.t2t
./shell/dialog/index-v2.t2t
./shell/dialog/index-v3.t2t
./shell/dialog/index-v4.t2t
./shell/dialog/index-v5.t2t
./shell/dialog/index-v6.t2t
```
